name: Monitor SDK Versions

on:
  schedule:
    - cron: '*/30 * * * *'  # Run every 30 minutes
  workflow_dispatch:

jobs:
  check-versions:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Check SDK versions
      id: version_check
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      run: |
        output=$(python -m utils.version_monitor)
        echo "changes_detected=$?" >> $GITHUB_OUTPUT

    - name: Trigger Documentation Pipeline
      if: steps.version_check.outputs.changes_detected == '1'
      uses: ./.github/workflows/reusable-documentation-pipeline.yml
      with:
        issue_title: '🔄 SDK Version Changes Detected'
        issue_body: |
          SDK version changes have been detected. Documentation validation has been triggered.
          
          Please review the validation results and update documentation if needed.
          
          Check the [workflow run](${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}) for details. 